# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wine_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'wine_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12wine_service.proto\x12\x04wine\"\x9c\x02\n\x0cWineFeatures\x12\x0f\n\x07\x61lcohol\x18\x01 \x01(\x01\x12\x12\n\nmalic_acid\x18\x02 \x01(\x01\x12\x0b\n\x03\x61sh\x18\x03 \x01(\x01\x12\x19\n\x11\x61lcalinity_of_ash\x18\x04 \x01(\x01\x12\x11\n\tmagnesium\x18\x05 \x01(\x01\x12\x15\n\rtotal_phenols\x18\x06 \x01(\x01\x12\x12\n\nflavanoids\x18\x07 \x01(\x01\x12\x1c\n\x14nonflavanoid_phenols\x18\x08 \x01(\x01\x12\x17\n\x0fproanthocyanins\x18\t \x01(\x01\x12\x17\n\x0f\x63olor_intensity\x18\n \x01(\x01\x12\x0b\n\x03hue\x18\x0b \x01(\x01\x12\x13\n\x0bod280_od315\x18\x0c \x01(\x01\x12\x0f\n\x07proline\x18\r \x01(\x01\"7\n\x0eWinePrediction\x12\x12\n\nprediction\x18\x01 \x01(\x05\x12\x11\n\twine_type\x18\x02 \x01(\t\"\x0f\n\rHealthRequest\"G\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\x0cmodel_loaded\x18\x03 \x01(\x08\x32\x86\x01\n\rWinePredictor\x12\x39\n\x0bPredictWine\x12\x12.wine.WineFeatures\x1a\x14.wine.WinePrediction\"\x00\x12:\n\x0b\x43heckHealth\x12\x13.wine.HealthRequest\x1a\x14.wine.HealthResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wine_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WINEFEATURES']._serialized_start=29
  _globals['_WINEFEATURES']._serialized_end=313
  _globals['_WINEPREDICTION']._serialized_start=315
  _globals['_WINEPREDICTION']._serialized_end=370
  _globals['_HEALTHREQUEST']._serialized_start=372
  _globals['_HEALTHREQUEST']._serialized_end=387
  _globals['_HEALTHRESPONSE']._serialized_start=389
  _globals['_HEALTHRESPONSE']._serialized_end=460
  _globals['_WINEPREDICTOR']._serialized_start=463
  _globals['_WINEPREDICTOR']._serialized_end=597
# @@protoc_insertion_point(module_scope)
